import "@/styles/globals.css";

import { redirect } from "next/navigation";
import { Toaster } from "sonner";

import { TRPCReactProvider } from "@/trpc/react";
import { getServerAuthSession } from "@/server/auth";

export const metadata = {
  title: "INC UMS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  if (!session?.user) return redirect("/");
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>
          <main className="p-10">{children}</main>
          <Toaster richColors />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
