import "@/styles/globals.css";

import { redirect } from "next/navigation";

import { getServerAuthSession } from "@/server/auth";

export const metadata = {
  title: "INC UMS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const ProtectedLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await getServerAuthSession();
  if (!session?.user) return redirect("/");
  return <main className="p-10">{children}</main>;
};

export default ProtectedLayout;
